version: "3.9"
# Create a custom build that can be re-used within Docker network
x-build-iota-core: &iota-core_build
  context: ${DOCKER_BUILD_CONTEXT:-../../}
  dockerfile: ${DOCKERFILE_PATH:-./Dockerfile}
services:

###################
# IOTA-CORE Nodes #
###################

  node-1-validator:
    build: *iota-core_build
    stop_grace_period: 1m
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    networks:
      - iota-core
    ports:
      - "8010:14265/tcp" # REST-API
      - "8011:8081/tcp" # Dashboard
      - "6011:6061/tcp" # pprof
      - "9019:9029/tcp" # INX
    volumes:
      - ./docker-network.snapshot:/app/data/snapshot.bin
      - ./config.json:/app/config.json:ro
    command: >
      ${COMMON_CONFIG}
      ${MANUALPEERING_CONFIG}
      --p2p.identityPrivateKey=08735375679f3d8031353e94282ed1d65119e5c288fe56d6639d9184a3f978fee8febfedff11cc376daea0f59c395ae2e9a870a25ac4e36093000fbf4d0e8f18
      --inx.enabled=true
      --inx.bindAddress=0.0.0.0:9029

  node-2-validator:
    image: docker-network-node-1-validator:latest
    stop_grace_period: 1m
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    networks:
      - iota-core
    ports:
      - "8020:14265/tcp" # REST-API
      - "8021:8081/tcp" # Dashboard
      - "6021:6061/tcp" # pprof
      - "9029:9029/tcp" # INX
    volumes:
      - ./docker-network.snapshot:/app/data/snapshot.bin
      - ./config.json:/app/config.json:ro
    command: >
      ${COMMON_CONFIG}
      ${MANUALPEERING_CONFIG}
      --p2p.identityPrivateKey=ba771419c52132a0dfb2521ed18667813f398da159010a55a0a482af939affb92d3338789ad4a07a7631b91791deb11f82ed5dc612822f24275e9f7a313b691f
      --inx.enabled=true
      --inx.bindAddress=0.0.0.0:9029

  node-3-validator:
    image: docker-network-node-1-validator:latest
    stop_grace_period: 1m
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    networks:
      - iota-core
    ports:
      - "8030:14265/tcp" # REST-API
      - "8031:8081/tcp" # Dashboard
      - "6031:6061/tcp" # pprof
      - "9039:9029/tcp" # INX
    volumes:
      - ./docker-network.snapshot:/app/data/snapshot.bin
      - ./config.json:/app/config.json:ro
    command: >
      ${COMMON_CONFIG}
      ${MANUALPEERING_CONFIG}
      --p2p.identityPrivateKey=a6261ac049755675ff1437654ca9f83b305055f01ff08c4f039209ef5a4a7d96d06fb61df77a8815209a8f4d204226dee593e50d0ec897ec440a2c1fbde77656
      --inx.enabled=true
      --inx.bindAddress=0.0.0.0:9029

  node-4:
    image: docker-network-node-1-validator:latest
    stop_grace_period: 1m
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    networks:
      - iota-core
    ports:
      - "8040:14265/tcp" # REST-API
      - "8041:8081/tcp" # Dashboard
      - "6041:6061/tcp" # pprof
      - "9049:9029/tcp" # INX
    volumes:
      - ./docker-network.snapshot:/app/data/snapshot.bin
      - ./config.json:/app/config.json:ro
    command: >
      ${COMMON_CONFIG}
      ${MANUALPEERING_CONFIG}
      --p2p.identityPrivateKey=03feb3bcd25e57f75697bb329e6e0100680431e4c45c85bc013da2aea9e9d0345e08a0c37407dc62369deebc64cb0fb3ea26127d19d141ee7fb8eaa6b92019d7
      --inx.enabled=true
      --inx.bindAddress=0.0.0.0:9029

  node-5:
    image: docker-network-node-1-validator:latest
    stop_grace_period: 1m
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    networks:
      - iota-core
    ports:
      - "8050:14265/tcp" # REST-API
      - "8051:8081/tcp" # Dashboard
      - "6051:6061/tcp" # pprof
      - "9059:9029/tcp" # INX
    volumes:
      - ./docker-network.snapshot:/app/data/snapshot.bin
      - ./config.json:/app/config.json:ro
    command: >
      ${COMMON_CONFIG}
      ${MANUALPEERING_CONFIG}
      --p2p.identityPrivateKey=7d1491df3ef334dee988d6cdfc4b430b996d520bd63375a01d6754f8cee979b855b200fbea8c936ea1937a27e6ad72a7c9a21c1b17c2bd3c11f1f6994d813446
      --inx.enabled=true
      --inx.bindAddress=0.0.0.0:9029

##################################################################
#  Monitoring                                                    #
##################################################################

  prometheus:
    image: prom/prometheus:latest
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      node-1-validator:
        condition: service_started
    networks:
      - iota-core
    ports:
      - "9090:9090" # prometheus
    secrets:
      - prometheus.yml
    command:
      - "--config.file=/run/secrets/prometheus.yml"
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:9.5.6
    restart: unless-stopped
    networks:
      - iota-core
    ports:
      - "3000:3000" # Grafana Dashboard
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana/:ro
    environment:
      - GF_ALERTING_ENABLED=true
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/local_dashboard.json
    profiles:
      - monitoring

##################
# INX Extensions #
##################

  inx-indexer:
    image: iotaledger/inx-indexer:2.0-alpha
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      node-1-validator:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    networks:
      - iota-core
    command: >
      --inx.address=node-1-validator:9019
      --restAPI.bindAddress=inx-indexer:9011

  inx-blockissuer:
    image: iotaledger/inx-blockissuer:1.0-alpha
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      node-1-validator:
        condition: service_healthy
      inx-indexer:
        condition: service_started
    networks:
      - iota-core
    environment:
      - "BLOCKISSUER_PRV_KEY=432c624ca3260f910df35008d5c740593b222f1e196e6cdb8cd1ad080f0d4e33997be92a22b1933f36e26fba5f721756f95811d6b4ae21564197c2bfa4f28270"
    command: >
      --inx.address=node-1-validator:9029
      --restAPI.bindAddress=inx-blockissuer:9086
      --blockIssuer.accountAddress=rms1prkursay9fs2qjmfctamd6yxg9x8r3ry47786x0mvwek4qr9xd9d5c6gkun
      --blockIssuer.proofOfWork.targetTrailingZeros=5

  inx-faucet:
    image: iotaledger/inx-faucet:2.0-alpha
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      node-1-validator:
        condition: service_healthy
      inx-indexer:
        condition: service_started
      inx-blockissuer:
        condition: service_started
    networks:
      - iota-core
    ports:
      - "8088:8091/tcp" # Faucet Frontend
    environment:
      - "FAUCET_PRV_KEY=de52b9964dda96564e9fab362ab16c2669c715c6a2a853bece8a25fc58c599755b938327ea463e0c323c0fd44f6fc1843ed94daecc6909c6043d06b7152e4737"
    command: >
      --inx.address=node-1-validator:9029
      --faucet.bindAddress=inx-faucet:8091
      --faucet.rateLimit.enabled=false

  inx-validator-1:
    image: iotaledger/inx-validator:latest
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      node-1-validator:
        condition: service_started
      inx-indexer:
        condition: service_started
    networks:
      - iota-core
    environment:
      - "VALIDATOR_PRV_KEY=443a988ea61797651217de1f4662d4d6da11fd78e67f94511453bf6576045a05293dc170d9a59474e6d81cfba7f7d924c09b25d7166bcfba606e53114d0a758b"
    command: >
      --logger.level=debug
      --inx.address=node-1-validator:9029
      --validator.ignoreBootstrapped=true
      --validator.accountAddress=rms1pzg8cqhfxqhq7pt37y8cs4v5u4kcc48lquy2k73ehsdhf5ukhya3y5rx2w6


  inx-validator-2:
    image: iotaledger/inx-validator:latest
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      node-2-validator:
        condition: service_started
      inx-indexer:
        condition: service_started
    networks:
      - iota-core
    environment:
      - "VALIDATOR_PRV_KEY=3a5d39f8b60367a17fd54dac2a32c172c8e1fd6cf74ce65f1e13edba565f281705c1de274451db8de8182d64c6ee0dca3ae0c9077e0b4330c976976171d79064"
    command: >
      --logger.level=debug
      --inx.address=node-2-validator:9029
      --validator.accountAddress=rms1pqm4xk8e9ny5w5rxjkvtp249tfhlwvcshyr3pc0665jvp7g3hc875k538hl

  inx-validator-3:
    image: iotaledger/inx-validator:latest
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      node-3-validator:
        condition: service_started
      inx-indexer:
        condition: service_started
    networks:
      - iota-core
    environment:
      - "VALIDATOR_PRV_KEY=db39d2fde6301d313b108dc9db1ee724d0f405f6fde966bd776365bc5f4a5fb31e4b21eb51dcddf65c20db1065e1f1514658b23a3ddbf48d30c0efc926a9a648"
    command: >
      --logger.level=debug
      --inx.address=node-3-validator:9029
      --validator.accountAddress=rms1pp4wuuz0y42caz48vv876qfpmffswsvg40zz8v79sy8cp0jfxm4kunflcgt


# Create our own network
networks:
  iota-core:
    driver: bridge

# Named Docker volumes for data persistence
volumes:
  grafana_data:

# read only files to load in the containers that may be shared across containers
secrets:
  prometheus.yml:
    file: ${PROMETHEUS_CONFIG:-./prometheus.yml}
